repos:
  - repo: local
    hooks:
      - id: rubocop
        name: rubocop
        entry: bin/rubocop
        language: system
        types: ['ruby']
        args: ['--autocorrect', '--force-exclusion']
